# This is a basic workflow that is manually triggered

name: Merge Blog Posts into Main Page

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [ main ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
    - run: pip install jinja
    - run: python3 gen.py
